### ISSUE TITLE
Grey / blue checkboxes coloring when only grey should be present

### ISSUE THREAD

**Issue by davidrabko** [daverbk/namelikepro#3]
<img width="293" alt="image" src="https://github.com/daverbk/namelikepro/assets/98875282/a4c7ed9b-eabd-4c89-9279-02e55ddf505f">

**Comment by Elovard** [comment]
The issue was fixed in https://github.com/daverbk/namelikepro/commit/d3a46b90d3f90879c427f8590605a8d10b0f49e8
